### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by ellisonleao** [ellisonleao/vl#11]
Idea:

A config file that overrides all the current flags. This is useful when you have a lot of whitelist links or ignored status codes

Something like:

.vl.yml

```yml
whitelist:
    - link1
    - link2
ignore:
    - 403
    - 404
```
